spring:
  application:
    name: HypeLink

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update


  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}

  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
        presigned-url-duration: ${S3_PRESIGNED_URL_DURATION}
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ${S3_REGION}

jwt:
  secret-key: ${JWT_KEY}
  access-token-expiration-ms: ${JWT_ACCESS}
  refresh-token-expiration-ms: ${JWT_REFRESH}

portone:
  api:
    secret: ${PORTONE_API_SECRET}
  store-id: ${PORTONE_STORE_ID}

websocket:
  allowed-origin: ${SERVER}
