spring:
  application:
    name: HypeLink

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG

jwt:
  secret-key: 123123123qweqweqwe123123123qwe123qwe12311111
  access-token-expiration-ms: 3600000
  refresh-token-expiration-ms: 604800000