spring:
  application:
    name: HypeLink

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret-key: ${JWT_KEY}
  access-token-expiration-ms: ${JWT_KEY}
  refresh-token-expiration-ms: ${JWT_KEY}