spring:
  application:
    name: HypeLink

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG

jwt:
  secret-key: ${JWT_KEY}
  access-token-expiration-ms: ${JWT_ACCESS}
  refresh-token-expiration-ms: ${JWT_REFRESH}