spring:
  application:
    name: HypeLink

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false


  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}

  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
        presigned-url-duration: ${S3_PRESIGNED_URL_DURATION}
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ${S3_REGION}

jwt:
  secret-key: ${JWT_KEY}
  access-token-expiration-ms: ${JWT_ACCESS}
  refresh-token-expiration-ms: ${JWT_REFRESH}

portone:
  api:
    secret: ${PORTONE_API_SECRET}
  store-id: ${PORTONE_STORE_ID}

naver:
  api:
    client-id: ${NAVER_MAP_CLIENT}
    client-secret: ${NAVER_MAP_SECRET}

websocket:
  allowed-origin: ${SERVER}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics  # 필요 시 "*" 로 전체 공개
      base-path: /api/health     # 기본값 (원하면 /api/health 로 커스터마이징 가능)
  endpoint:
    health:
      show-details: always     # 상세 상태 보기 (디버깅에 유용)
  metrics:
    tags:
      application: hypelink
